name: JSON Validation

on:
  push:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'
  pull_request:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate questions JSON
        run: >
          ajv validate
          -s assets/datasets/question_catalog_schema.json
          -d assets/datasets/question_catalog.json
          --spec=draft2020
          --strict=false

      - name: Validate map features JSON
        run: >
          ajv validate
          -s assets/datasets/map_feature_collection_schema.json
          -d assets/datasets/map_feature_collection.json
          --spec=draft2020
          --strict=false
